project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  description: Portfolio
  site-url: "https://WillYum-Sea.github.io/STA9750-2026-FALL/"
  
  sidebar:
    style: "docked"
    search: false
    contents:
      - text: "Home"
        href: index.qmd
        
      - text: "About"
        href: pages/about.qmd
        
      - text: "Projects"
        href: pages/projects.qmd
        
      - text: "Résumé"
        href: pages/resume.qmd

format:
  html:
    css: styles.css
    toc: false

editor:
  mode: source