project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  description: Portfolio
  site-url: "https://WillYum-Sea.github.io/STA9750-2026-FALL/"
  
  sidebar:
    style: "docked"
    search: false
    contents:
      - text: "Home"
        href: index.qmd
        
      - text: "About"
        href: pages/about.qmd
        
      - text: "Projects"
        href: pages/projects.qmd
        
      - section: "Course Work"
        expanded: false
        contents:
          - text: "Project 1"
            href: pages/mp01.qmd
          
          - text: "Project 2"
            href: pages/mp02.qmd
            
          - text: "Project 3"
            href: pages/mp03.qmd
            
          - text: "Project 4"
            href: pages/mp04.qmd
        
      - text: "Résumé"
        href: pages/resume.qmd

format:
  html:
    css: styles.css
    toc: false

editor:
  mode: source